name: dominoes_tracker
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  get_it: ^7.6.4
  google_fonts: ^6.1.0
  equatable: ^2.0.5
  firebase_core: ^2.24.2
  cloud_firestore: ^4.14.0
  go_router: ^12.1.3
  dartz: ^0.10.1
  flutter_screenutil: ^5.9.3
  cached_network_image: ^3.4.1
  skeletonizer: ^2.1.2
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

